name: wordherd
version: 0.2.0
author: Dart DevRel
description: GAME
homepage: https://github.com/johnmccutchan/tilebasedwordsearch
dependencies:
  asset_pack: any
  benchmark_harness: any
  browser: any
  crypto: any
  http_server: any
  game_loop: any
#  google_appstate_v1_api:
#    git: https://github.com/financeCoding/dart_appstate_v1_api_client.git
#  google_games_v1_api:
#    git: https://github.com/financeCoding/dart_games_v1_api_client.git
#  google_plus_v1_api:
#    git: https://github.com/financeCoding/dart_plus_v1_api_client.git
  html5lib: any
  http: any
  intl: any
  lawndart: any
  logging: any
  postgresql: any
  start: any
  unittest: any
  polymer: any
  route: any
  path: any
  serialization: any