// Auto-generated from high_scores_component.html.
// DO NOT EDIT.

library high_scores_panel;

import 'dart:html' as autogenerated;
import 'dart:svg' as autogenerated_svg;
import 'package:web_ui/web_ui.dart' as autogenerated;
import 'package:web_ui/observe/observable.dart' as __observe;
import 'package:web_ui/web_ui.dart';
import '../tilebasedwordsearch.dart' as app;



class HighScoresComponent extends WebComponent {
  /** Autogenerated from the template. */

  autogenerated.ScopedCssMapper _css;

  /** This field is deprecated, use getShadowRoot instead. */
  get _root => getShadowRoot("high-scores-panel");
  static final __html1 = new autogenerated.Element.html('<ul>\n            <template></template>\n          </ul>'), __html2 = new autogenerated.LIElement(), __shadowTemplate = new autogenerated.DocumentFragment.html('''
        <h2>High Scores</h2>
        <template></template>
        <template></template>
          <button>New game</button>
          <button>Home</button>
      ''');
  autogenerated.ButtonElement __e23, __e24;
  autogenerated.Element __e21, __e22;
  autogenerated.Template __t;

  void created_autogenerated() {
    var __root = createShadowRoot("high-scores-panel");
    setScopedCss("high-scores-panel", new autogenerated.ScopedCssMapper({"high-scores-panel":"[is=\"high-scores-panel\"]"}));
    _css = getScopedCss("high-scores-panel");
    __t = new autogenerated.Template(__root);
    __root.nodes.add(__shadowTemplate.clone(true));
    __e21 = __root.nodes[3];
    __t.conditional(__e21, () => highScores.length > 0, (__t) {
      var __e19, __e20;
      __e20 = __html1.clone(true);
      __e19 = __e20.nodes[1];
      __t.loop(__e19, () => highScores, ($list, $index, __t) {
        var score = $list[$index];
        var __e18;
        __e18 = __html2.clone(true);
        var __binding17 = __t.contentBind(() =>  score , false);
        __e18.nodes.add(__binding17);
      __t.addAll([new autogenerated.Text('\n              '),
          __e18,
          new autogenerated.Text('\n            ')]);
      });
    __t.addAll([new autogenerated.Text('\n          '),
        __e20,
        new autogenerated.Text('\n        ')]);
    });

    __e22 = __root.nodes[5];
    __t.conditional(__e22, () => highScores.length <= 0, (__t) {
    __t.add(new autogenerated.Text('\n          No high scores yet.\n        '));
    });

    __e23 = __root.nodes[7];
    __t.listen(__e23.onClick, ($event) { app.currentPanel='newGame'; });
    __e24 = __root.nodes[9];
    __t.listen(__e24.onClick, ($event) { app.currentPanel='main'; });
    __t.create();
  }

  void inserted_autogenerated() {
    __t.insert();
  }

  void removed_autogenerated() {
    __t.remove();
    __t = __e21 = __e22 = __e23 = __e24 = null;
  }

  /** Original code from the component. */

  List<int> highScores = <int>[];
}
//# sourceMappingURL=high_scores_component.dart.map