// Auto-generated from new_game_panel.html.
// DO NOT EDIT.

library new_game_panel;

import 'dart:html' as autogenerated;
import 'dart:svg' as autogenerated_svg;
import 'package:web_ui/web_ui.dart' as autogenerated;
import 'package:web_ui/observe/observable.dart' as __observe;
import 'package:web_ui/web_ui.dart';
import '../tilebasedwordsearch.dart' as app;



// New Game Panel is the view when user has clicked new game from Main Panel
// Includes:
// - opponents, integration to G+
// - leaderboard or high score google api
class NewGamePanel extends WebComponent {
  /** Autogenerated from the template. */

  autogenerated.ScopedCssMapper _css;

  /** This field is deprecated, use getShadowRoot instead. */
  get _root => getShadowRoot("new-game-panel");
  static final __shadowTemplate = new autogenerated.DocumentFragment.html('''
        <h2>New Game Panel</h2>
        <div>
          <button>Start Game</button>
          <button>Cancel</button>
        </div>
      ''');
  autogenerated.ButtonElement __e27, __e28;
  autogenerated.Template __t;

  void created_autogenerated() {
    var __root = createShadowRoot("new-game-panel");
    setScopedCss("new-game-panel", new autogenerated.ScopedCssMapper({"new-game-panel":"[is=\"new-game-panel\"]"}));
    _css = getScopedCss("new-game-panel");
    __t = new autogenerated.Template(__root);
    __root.nodes.add(__shadowTemplate.clone(true));
    __e27 = __root.nodes[3].nodes[1];
    __t.listen(__e27.onClick, ($event) { app.currentPanel = 'game'; });
    __e28 = __root.nodes[3].nodes[3];
    __t.listen(__e28.onClick, ($event) { app.currentPanel = 'main'; });
    __t.create();
  }

  void inserted_autogenerated() {
    __t.insert();
  }

  void removed_autogenerated() {
    __t.remove();
    __t = __e27 = __e28 = null;
  }

  /** Original code from the component. */


}
//# sourceMappingURL=new_game_panel.dart.map