// Auto-generated from word_list.html.
// DO NOT EDIT.

library word_list;

import 'dart:html' as autogenerated;
import 'dart:svg' as autogenerated_svg;
import 'package:web_ui/web_ui.dart' as autogenerated;
import 'package:web_ui/observe/observable.dart' as __observe;
import 'package:web_ui/web_ui.dart';
import '../tilebasedwordsearch.dart' as app;



@observable
class WordListComponent extends WebComponent {
  /** Autogenerated from the template. */

  autogenerated.ScopedCssMapper _css;

  /** This field is deprecated, use getShadowRoot instead. */
  get _root => getShadowRoot("word-list");
  static final __html1 = new autogenerated.Element.html('<ul>\n            <template></template>\n          </ul>'), __html2 = new autogenerated.LIElement(), __html3 = new autogenerated.Element.html('<span class="score"></span>'), __shadowTemplate = new autogenerated.DocumentFragment.html('''
        <template></template>
      ''');
  autogenerated.Element __e63;
  autogenerated.Template __t;

  void created_autogenerated() {
    var __root = createShadowRoot("word-list");
    setScopedCss("word-list", new autogenerated.ScopedCssMapper({"word-list":"[is=\"word-list\"]"}));
    _css = getScopedCss("word-list");
    __t = new autogenerated.Template(__root);
    __root.nodes.add(__shadowTemplate.clone(true));
    __e63 = __root.nodes[1];
    __t.conditional(__e63, () => !app.board.recentWords.isEmpty, (__t) {
      var __e61, __e62;
      __e62 = __html1.clone(true);
      __e61 = __e62.nodes[1];
      __t.loop(__e61, () => app.board.recentWords, ($list, $index, __t) {
        var word = $list[$index];
        var __e59, __e60;
        __e60 = __html2.clone(true);
        var __binding57 = __t.contentBind(() => word, false);
        __e59 = __html3.clone(true);
        var __binding58 = __t.contentBind(() => scoreFor($index), false);
        __e59.nodes.add(__binding58);
        __e60.nodes.addAll([__binding57,
            new autogenerated.Text(' '),
            __e59]);
      __t.addAll([new autogenerated.Text('\n              '),
          new autogenerated.Text('\n              '),
          __e60,
          new autogenerated.Text('\n            ')]);
      });
    __t.addAll([new autogenerated.Text('\n          '),
        __e62,
        new autogenerated.Text('\n        ')]);
    });

    __t.create();
  }

  void inserted_autogenerated() {
    __t.insert();
  }

  void removed_autogenerated() {
    __t.remove();
    __t = __e63 = null;
  }

  /** Original code from the component. */

  
  String scoreFor(int index) {
    return app.board.words[app.board.recentWords[index]].toString();
  }
}
//# sourceMappingURL=word_list.dart.map